#!/bin/sh

if [ `dirname "$0"` != "." ]; then
	echo "you have run this script from the dir it is placed in"
	exit 1
elif [ -z "$1" ]; then
	echo "usage: $0 rhel6|rhel7|rhel8|rhel9"
	exit 1
fi

rm -f /usr/src/redhat/SOURCES/atomiadns-*
rm -f /usr/src/redhat/SPECS/atomiadns-*
cp SPECS/*.spec /usr/src/redhat/SPECS

startdir="$PWD"

cd ..
tar cfpz /usr/src/redhat/SOURCES/atomiadns-syncer.tar.gz --exclude "*/.svn" syncer

cd /usr/src/redhat/SPECS

# New way to build packages that supports RHEL6-9
OS="$1"
OS_VERSION=`echo "$OS" | awk '{print tolower($0)}' | awk -Frhel '{ print $2 }'`
echo "INFO: OS is $OS"
PACKAGES="atomiadns-nameserver.spec"
for PACKAGE_SPEC in $PACKAGES; do
	PACKAGE_NAME=`echo $PACKAGE_SPEC | awk -F. '{ print $1 }'`
	echo "INFO: Running rpmbuild for $PACKAGE_NAME"
	if [ "$OS_VERSION" -lt 8 ]; then
		# Build and sign pacakages in older RHEL versions
		rpmbuild --sign -ba "$PACKAGE_SPEC"
		if [ $? -ne 0 ]; then
			echo "ERROR: Could not run rpmbuild!"
			exit $ret
		fi
	else
		# Build packages
		rpmbuild -ba "$PACKAGE_SPEC"
		if [ $? -ne 0 ]; then
			echo "ERROR: Could not run rpmbuild!"
			exit $ret
		fi
		# Sign built package
		echo "INFO: Signing package"
		rpm --addsign /usr/src/redhat/RPMS/*/"$PACKAGE_NAME"*.rpm
		if [ $? -ne 0 ]; then
			echo "ERROR: Could not sign package!"
			exit $ret
		fi
	fi
done

cd "$startdir"
cp /usr/src/redhat/RPMS/*/atomiadns-* ..
cp /usr/src/redhat/SRPMS/atomiadns-* ..
rm -f ../*-debuginfo-*
