#!/bin/sh
rm -f *deb
dpkg-buildpackage -rfakeroot -tc -us -uc
ret=$?
if [ $ret != 0 ]; then
	exit $ret
fi

mv ../*deb .
rm ../atomiadns-*
mv *deb ..

if [ -d "client" ]; then
	cd client && make distclean
fi
