#!/bin/sh

if [ `dirname "$0"` != "." ]; then
	echo "you have run this script from the dir it is placed in"
	exit 1
elif [ -z "$1" ]; then
	echo "usage: $0 rhel6|rhel7|rhel8|rhel9"
	exit 1
fi

# Include the helpers
source ../build-helpers.sh

rm -f /usr/src/redhat/SOURCES/atomiadns-*
rm -f /usr/src/redhat/SPECS/atomiadns-*
cp SPECS/*.spec /usr/src/redhat/SPECS

startdir="$PWD"

cd ..
tar cfpz /usr/src/redhat/SOURCES/atomiadns-zoneimport.tar.gz --exclude "*/.svn" zonefileimporter

cd /usr/src/redhat/SPECS

# New way to build packages that supports RHEL6-9
PACKAGES="atomiadns-zoneimport.spec"
build_rpm_helper "$1" "$PACKAGES"
ret=$?
if [ $ret -ne 0 ]; then
	exit $ret
fi

cd "$startdir"
cp /usr/src/redhat/RPMS/*/atomiadns-* ..
rm -f ../*-debuginfo-*
