#!/bin/sh

### BEGIN INIT INFO
# Provides:          atomiadyndns
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $network $syslog
# Should-Stop:       $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the Atomia DNS DDNS server
# Description:       The Atomia DNS DDNS server is an application that accepts DDNS requests, authorizes them and then perform updates using the SOAP API.
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions
DISTRO=$(lsb_release -is 2>/dev/null || echo Debian)

case "$1" in
    start)
	log_daemon_msg "Starting Atomia DNS DDNS server." "atomiadyndns"

	if [ ! -x /usr/bin/atomiadyndns ]; then
	    log_action_msg "atomiadyndns binary missing - not starting"
	    log_end_msg 1
	    exit 1
	fi

	if start-stop-daemon	--start --name atomiadyndns --background \
				--startas /bin/sh --user daemon --chuid daemon -- -c "atomiadyndns 2>&1 | logger -t atomiadyndns"; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    stop)
	log_daemon_msg "Stopping Atomia DNS DDNS server." "atomiadyndns"

	if start-stop-daemon	--stop --quiet --name atomiadyndns --user daemon; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    
    *)
	log_action_msg "Usage: $0 {start|stop}"
	exit 1
    ;;
esac

exit 0
