#!/bin/sh

if [ `dirname "$0"` != "." ]; then
	echo "you have run this script from the dir it is placed in"
	exit 1
elif [ -z "$1" ]; then
	echo "usage: $0 rhel4|rhel5"
	exit 1
fi

rm -f /usr/src/redhat/SOURCES/atomiadns-*
rm -f /usr/src/redhat/SPECS/atomiadns-*
cp SPECS/*.spec /usr/src/redhat/SPECS

startdir="$PWD"

cd ..
tar cfpz /usr/src/redhat/SOURCES/atomiadns-dyndns.tar.gz --exclude "*/.svn" dyndns

cd /usr/src/redhat/SPECS
rpmbuild --sign -ba atomiadns-dyndns.spec
ret=$?

cd "$startdir"
cp /usr/src/redhat/RPMS/*/atomiadns-* ..
cp /usr/src/redhat/SRPMS/atomiadns-* ..
rm -f ../*-debuginfo-*
exit $ret
