#!/bin/sh

### BEGIN INIT INFO
# Provides:          atomiadns-nameserver-updated
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $network $syslog
# Should-Stop:       $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the Atomia DNS Syncer
# Description:       The Atomia DNS Syncer is an application syncing DNS Data via SOAP to a local BDB database
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions
DISTRO=$(lsb_release -is 2>/dev/null || echo Debian)

case "$1" in
    start)
	log_daemon_msg "Starting Atomia DNS Syncer." "atomiadnssync updated"

	if [ ! -x /usr/bin/atomiadnssync ]; then
	    log_action_msg "atomiadnssync binary missing - not starting"
	    log_end_msg 1
	    exit 1
	fi

	if start-stop-daemon	--start --name atomiadnssync --background \
				--startas /bin/sh --user bind --chuid bind -- -c "atomiadnssync updated 2>&1 | logger -t atomiadnssync_updated"; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi

	if start-stop-daemon	--start --name atomiadnssync_eventchain --background \
					--startas /bin/sh --user bind --chuid bind -- -c "atomiadnssync eventchain 2>&1 | logger -t atomiadnssync_eventchain"; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    stop)
	log_daemon_msg "Stopping Atomia DNS Syncer." "atomiadnssync updated"

	if start-stop-daemon	--stop --quiet --name atomiadnssync --user bind; then
	    log_end_msg 0
	else
	    log_end_msg 1
	fi
    ;;

    restart)
	$0 stop
	sleep 1
	$0 start
    ;;
    
    *)
	log_action_msg "Usage: $0 {start|stop}"
	exit 1
    ;;
esac

exit 0
