#!/bin/sh

mkdir -p /var/lib/bind/atomiadns_bdb || exit 1
chown bind:bind /var/lib/bind/atomiadns_bdb

cat > /etc/default/bind9 <<EOF
OPTIONS="-u bind"
RESOLVCONF="no"
EOF

mkdir -p /etc/bind/slave/zones
chown -R bind:bind /etc/bind/slave

touch /etc/bind/slave/named-slavezones.conf.local
chown bind:bind /etc/bind/slave/named-slavezones.conf.local
