#!/bin/sh

cat > /etc/default/bind9 <<EOF
OPTIONS="-u bind"
RESOLVCONF="no"
EOF

if [ -f /etc/atomiadns.conf ]; then
	if [ -z "$(grep "slavezones_config" /etc/atomiadns.conf)" ]; then
		cat /usr/share/atomia/conf/atomiadns-debian.conf >> /etc/atomiadns.conf
	fi
else
        cp /usr/share/atomia/conf/atomiadns-debian.conf /etc/atomiadns.conf
fi

if [ ! -f /etc/bind/atomiadns.named.conf ]; then
	cp -fp /usr/share/atomiadns/atomiadns.named.conf /etc/bind/atomiadns.named.conf 
fi

if [ -z "$(grep '/etc/bind/atomiadns.named.conf' /etc/bind/named.conf.local)" ]; then
	echo 'include "/etc/bind/atomiadns.named.conf";' >> /etc/bind/named.conf.local
fi

mkdir -p /etc/bind/slaves/zones
chown -R bind:bind /etc/bind/slaves

touch /etc/bind/slaves/named-slavezones.conf.local
chown bind:bind /etc/bind/slaves/named-slavezones.conf.local

touch /etc/bind/tsig_keys.conf
chown bind:bind /etc/bind/tsig_keys.conf
